name: "🐞 Bug Report"
description: "버그를 신고하세요."
title: "[Bug] 버그 설명"
labels: ["bug"]
body:
  - type: input
    id: steps
    attributes:
      label: "재현 방법"
      placeholder: "버그를 재현할 수 있는 단계"
  - type: input
    id: expected
    attributes:
      label: "예상 동작"
      placeholder: "예상했던 동작"
  - type: input
    id: actual
    attributes:
      label: "실제 동작"
      placeholder: "실제로 발생한 동작"
