name: "🚀 Feature Request"
description: "새로운 기능을 제안하세요."
title: "[Feature] 제안할 기능"
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: "기능 요약"
      placeholder: "기능에 대한 간단한 설명"
      required: true
  - type: textarea
    id: details
    attributes:
      label: "세부 설명"
      placeholder: "기능이 어떻게 동작해야 하는지 설명"
  - type: input
    id: purpose
    attributes:
      label: "필요한 이유"
      placeholder: "왜 이 기능이 필요한가요?"
