name: "Modify"
description: "수정할내용 을 입력하세요."
title: "[Modify] 수정할내용"
labels: ["modify"]
body:
  - type: input
    id: summary
    attributes:
      label: "수정할내용"
      placeholder: "수정한 내용에 대한 간단한 설명"
  - type: textarea
    id: details
    attributes:
      label: "세부 설명"
      placeholder: "기능이 어떻게 동작해야 하는지 설명"
  - type: input
    id: purpose
    attributes:
      label: "필요한 이유"
      placeholder: "왜 이 기능이 필요한가요?"
