name: "✅ Task"
description: "할 일을 작성하세요."
title: "[Task] 작업 내용"
labels: ["task"]
body:
  - type: input
    id: task
    attributes:
      label: "작업 설명"
      placeholder: "무엇을 해야 하나요?"
  - type: textarea
    id: details
    attributes:
      label: "세부 내용"
      placeholder: "세부 작업 내용 또는 참고 사항"
